-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS cosmic_finance.accounts
(
    account_id bigserial,
    customer_id integer,
    balance bigint,
    account_status text,
    account_type text,
    currency text,
    created_at timestamp with time zone,
    modified_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT accounts_pkey PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS cosmic_finance.customers
(
    customer_id bigserial,
    first_name text,
    last_name text,
    city text,
    mobile_no text,
    pancard_no text,
    dob text,
    created_at timestamp with time zone,
    modified_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT customers_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS cosmic_finance.loans
(
    loan_id bigserial,
    customer_id integer,
    branch_id integer,
    loan_amount bigint,
    date_issued date,
    created_at timestamp with time zone,
    modified_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT loans_pkey PRIMARY KEY (loan_id)
);

CREATE TABLE IF NOT EXISTS cosmic_finance.branches
(
    branch_id bigserial,
    branch_name text,
    branch_location text,
    created_at timestamp with time zone,
    modified_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT branches_pkey PRIMARY KEY (branch_id)
);

CREATE TABLE IF NOT EXISTS cosmic_finance.transactions
(
    transaction_id bigserial,
    transaction_type text,
    from_account_id bigint,
    to_account_id bigint,
    date_issued date,
    amount bigint,
    transaction_medium text,
    created_at timestamp with time zone,
    modified_at timestamp with time zone,
    deleted_at timestamp with time zone,
    CONSTRAINT transactions_pkey PRIMARY KEY (transaction_id)
);

ALTER TABLE IF EXISTS cosmic_finance.accounts
    ADD CONSTRAINT accounts_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES cosmic_finance.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS cosmic_finance.loans
    ADD CONSTRAINT loans_branch_id_fkey FOREIGN KEY (branch_id)
    REFERENCES cosmic_finance.branches (branch_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS cosmic_finance.loans
    ADD CONSTRAINT loans_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES cosmic_finance.customers (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS cosmic_finance.transactions
    ADD CONSTRAINT transactions_from_account_id_fkey FOREIGN KEY (from_account_id)
    REFERENCES cosmic_finance.accounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS transactions_from_account_id_idx
    ON cosmic_finance.transactions(from_account_id);


ALTER TABLE IF EXISTS cosmic_finance.transactions
    ADD CONSTRAINT transactions_to_account_id_fkey FOREIGN KEY (to_account_id)
    REFERENCES cosmic_finance.accounts (account_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS transactions_to_account_id_idx
    ON cosmic_finance.transactions(to_account_id);

END;